# Generated by Django 5.1.7 on 2025-03-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_patient_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_info',
            field=models.CharField(max_length=10),
        ),
    ]
